version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./health-management-frontend
    ports:
      - "3000:3000"
    environment:
      - BASE_URL_USERS_API=http://users-api:8180
      - BASE_URL_MEDICAL_API=http://medical-api:8280
      - BASE_URL_LABS_API=http://labs-api:8380
    depends_on:
      - users-api
      # - medical-api
      - labs-api
    networks:
      - frontend-svc-networks
  users-api:
    container_name: users-api
    build: ./health-management-user-api
    ports:
      - "8180:8180"
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/users
      - DATABASE_USER=my_user
      - DATABASE_PASSWORD=password123
      - ENVIRONMENT=production
    depends_on:
      - database
    networks:
      - services-api-networks
      - frontend-svc-networks
  # medical-api:
  #   container_name: medical-api
  #   build: ./health-management-medical-api
  #   ports:
  #     - "8280:8280"
  #   environment:
  #     - DATABASE_URL=jdbc:postgresql://database:5432/medical
  #     - DATABASE_USER=my_user
  #     - DATABASE_PASSWORD=password123
  #     - ENVIRONMENT=production
  #   depends_on:
  #     - database
  #   networks:
  #     - services-api-networks
  #     - frontend-svc-networks
  labs-api:
    container_name: labs-api
    build: ./health-management-labs-api
    ports:
      - "8380:8380"
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/labs
      - DATABASE_USER=my_user
      - DATABASE_PASSWORD=password123
      - ENVIRONMENT=production
    depends_on:
      - database
    networks:
      - services-api-networks
      - frontend-svc-networks
  database:
    container_name: postgresql_db
    image: bitnami/postgresql:15.2.0
    environment:
      - POSTGRESQL_DATABASE=users
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
    ports:
      - "5432:5432"
    networks:
      - services-api-networks
networks:
  services-api-networks:
  frontend-svc-networks:
    
